// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  // These slices include WebGL and animation code. Rendering them only in the
  // browser keeps Next's server render from trying to initialize that stack.
  alternating_text: dynamic(() => import("./AlternatingText"), { ssr: false }),
  big_text: dynamic(() => import("./BigText"), { ssr: false }),
  carousel: dynamic(() => import("./Carousel"), { ssr: false }),
  hero: dynamic(() => import("./Hero"), { ssr: false }),
  sky_dive: dynamic(() => import("./SkyDive"), { ssr: false }),
};
